version: '3.3'
services:
  mysql:
    image: mysql
    volumes:
    - data:/var/lib/mysql
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
    - 3306:3306
  grimoire:
    build: .
    ports:
    - 8080:8080
volumes:
  data: